### ISSUE TITLE
Requirements.txt need attention

### ISSUE THREAD

**Issue by Drmoca** [alyosama/virnet#1]
![image](https://user-images.githubusercontent.com/7161111/54584284-940f8f00-4a1f-11e9-96c3-3cee35906b8f.png)

**Comment by alyosama** [comment]
I have fixed it. Take a look and let me know what happens ( I did this fix, while i was waiting Dr. Neveen. So, it might not work )

**Comment by Drmoca** [comment]
Still not working, can you recheck!

**Comment by alyosama** [comment]
@Drmoca  Could you send me the error you got? because i rechecked it and it was okay.
