### ISSUE TITLE
Question about result

### ISSUE THREAD

**Issue by quliping** [alyosama/virnet#10]
![image](https://user-images.githubusercontent.com/39583607/196029922-5ddb2e5c-85e8-4d6b-9c05-33a6f0b3d80a.png)
Hello, I don't understand the result from virnet. Which sequence should be considered to be from a virus, sequence with result '0' or '1'? What should be the threshold of the score, and what does the score mean?

Looking forward to your reply. 

Sincerely,

Liping Qu

**Comment by alyosama** [comment]
Sequences with 1. the threshold is 0.5. 
The score is probability of the read if it is viral or not viral
