### ISSUE TITLE
work on contigs (2.5kbup); result 

### ISSUE THREAD

**Issue by Ruonan0101** [alyosama/virnet#2]
Dear developers, 
I have two quick questions. 
1) will virnet work on the contigs with length greater than 2.5kb by using --input_dim=3000;
2) after running on my test file, I have problem to interperate the results. what 'score' in the 4th column refers to and what does the '1' and '0' in result mean. I assume it is binary , present or not and want to confirm with you. Thanks~

**Comment by alyosama** [comment]
Dear @Ruonan0101,
1. we didn't use it 3000 model with 2.5kb before but I think it will work. Let me know what will you find. 
Instead you can make all contigs with 1000kb and run the tool with --input_dim=1000. 

2. The score is the classifier probability of classify the read to viral or not viral. (1 is viral and 0 is not viral(bacteria or archaea) 

Let me know if you need anything else.
