### ISSUE TITLE
Requirements.txt Problems

### ISSUE THREAD

**Issue by schackartk** [alyosama/virnet#9]
The file `requirments.txt` is a misspelling of "requirements.txt" (the first "e" is missing in the file name.)

Also, pip3 doesn't seem to recognize `pickle`. The following occurs:
```
$ pip3 install pickle
> ERROR: Could not find a version that satisfies the requirement pickle
> ERROR: No matching distribution found for pickle
```
I have found [pickle5](https://pypi.org/project/pickle5/) and [pickle-mixin](https://pypi.org/project/pickle-mixin/) on PyPi. Which pickle should be installed for compatibility to this tool?

**Comment by schackartk** [comment]
On a related note, your README instructions for installing dependencies is incorrect. The `-r` flag must be included:

```
pip3 install -r requirments.txt
```

And once the file name has been fixed, it will be 
```
pip3 install -r requirements.txt
```

**Comment by alyosama** [comment]
Thank you @schackartk. I have added -r flag in the documentation
Actually, I am not maintaining the package anymore as I am working on other projects. 
Feel free to add a pull request of any changes and I will approve it.

**Comment by schackartk** [comment]
Thanks for updating the documentation, but the original issue still stands. I am not sure what version of pickle the tool uses. I also have some issues due to ambiguity in the version number of the other requirements.
